name: GTASA GPS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Android NDK (r25c)
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
        local-cache: true

    - name: Build with ndk-build
      run: |
        ndk-build NDK_PROJECT_PATH=. \
        APP_BUILD_SCRIPT=./Android.mk \
        APP_APPLICATION_MK=./Application.mk \
        APP_PLATFORM=android-21 \
        NDK_DEBUG=0

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: GTASA_GPS_output
        path: libs/
