name: AML Mod Compiler

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository...
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Download mod template
      uses: wei/wget@v1
      with:
        args: -O ./AML_src.zip https://github.com/RusJJ/AndroidModLoader/archive/refs/heads/main.zip

    - name: Install template
      run: |
        unzip ./AML_src.zip
        mv ./AndroidModLoader-main/mod ./mod

    - name: Download structs from public repo
      uses: actions/checkout@v4
      with:
        repository: AndroidModLoader/GTASA_GPS
        path: public_structs

    - name: Move structs to project
      run: mv public_structs/* ./

    - name: Install Android NDK (r25c)
      uses: nttld/setup-ndk@v1.2.0
      with:
        ndk-version: r25c
        local-cache: true

    - name: Build the code
      run: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk NDK_DEBUG=0 -j12

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-mod
        path: ./libs