name: AML Mod Compiler

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Download AML template
      uses: wei/wget@v1
      with:
        args: -O ./AML_src.zip https://github.com/RusJJ/AndroidModLoader/archive/refs/heads/main.zip

    - name: Install AML template
      run: |
        unzip ./AML_src.zip
        mv ./AndroidModLoader-main/mod ./mod

    - name: Download public structs
      uses: actions/checkout@v4
      with:
        repository: AndroidModLoader/GTASA_GPS
        path: public_structs

    - name: Move required struct files
      run: |
        cp public_structs/GTASA_STRUCTS* ./
        cp -r public_structs/AArch64_ModHelper ./

    - name: Install Android NDK (r25c)
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c

    - name: Build
      run: |
        ndk-build \
        APP_PLATFORM=android-21 \
        NDK_PROJECT_PATH=. \
        APP_BUILD_SCRIPT=./Android.mk \
        APP_APPLICATION_MK=./Application.mk \
        -j12

    - name: Upload compiled output
      uses: actions/upload-artifact@v4
      with:
        name: GTASA_GPS_Build
        path: libs/